config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(
      :name, :address, :description, :price_per_night, :number_of_guests
    )
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>

<%= f.input :name %>
<%= f.input :address %>
<%= f.input :description%>
<%= f.input :price_per_night %>
<%= f.input :number_of_guests %>

<%= f.submit %>
<% end %>

app/views/flats/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-10">
      <h1>Simple Airbnb</h1>
    </div>
    <div class="col-lg-2 text-right">
      <%= link_to 'New Flat', new_flat_path %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="cards cards-grid mt-3 mb-3">
      <% @flats.each do |flat| %>
         <%= link_to flat_path(flat) do%>
        <div class="card-product">
          <!-- images -->
          <img src="https://picsum.photos/300" alt="">
          <div class="card-product-infos">
            <h2>Name: <%= flat.name %></h2>
            <p>Address: <%= flat.address %></p>
            <br>
            <p><i class="material-icons mr-2">euro_symbol</i><%= flat.price_per_night %>, <i class="material-icons mr-2">people</i>: <%= flat.number_of_guests %></p>
          </div>
        </div>
        <% end %>
      <% end %>  
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  
  <h1>Flat creation</h1>
  <%= render 'form', flat: @flat %>

</div>

app/views/flats/show.html.erb
<div class="container">
  <img src="https://picsum.photos/300" alt="">
  <h1>Name: <%= @flat.name %></h1>
  <p>Located in <%= @flat.address %></p>
  <p>Price: <%= @flat.price_per_night %></p>
  <p>Number of peoples <%= @flat.number_of_guests %> max</p>
    <%= link_to 'Back to flat', flats_path(@flat) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>